// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: network.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message_Type int32

const (
	Message_GET_BLOCK                Message_Type = 0
	Message_GET_BLOCK_ACK            Message_Type = 1
	Message_CONSENSUS                Message_Type = 2
	Message_FETCH_CERT               Message_Type = 3
	Message_FETCH_CERT_ACK           Message_Type = 4
	Message_FETCH_BLOCK_SIGN         Message_Type = 5
	Message_FETCH_BLOCK_SIGN_ACK     Message_Type = 6
	Message_FETCH_IBTP_REQUEST_SIGN  Message_Type = 7
	Message_FETCH_IBTP_RESPONSE_SIGN Message_Type = 8
	Message_FETCH_IBTP_SIGN_ACK      Message_Type = 9
	Message_GET_ADDRESS              Message_Type = 11
	Message_GET_ADDRESS_ACK          Message_Type = 12
	Message_GET_BLOCK_HEADERS        Message_Type = 13
	Message_GET_BLOCK_HEADERS_ACK    Message_Type = 14
	Message_GET_BLOCKS               Message_Type = 15
	Message_GET_BLOCKS_ACK           Message_Type = 16
	Message_CHECK_MASTER_PIER        Message_Type = 17
	Message_CHECK_MASTER_PIER_ACK    Message_Type = 18
	Message_FETCH_BURN_SIGN          Message_Type = 21
	Message_FETCH_BURN_SIGN_ACK      Message_Type = 22
	//pier message
	Message_APPCHAIN_REGISTER       Message_Type = 23
	Message_APPCHAIN_UPDATE         Message_Type = 24
	Message_APPCHAIN_GET            Message_Type = 25
	Message_INTERCHAIN_META_GET     Message_Type = 26
	Message_RULE_DEPLOY             Message_Type = 27
	Message_IBTP_GET                Message_Type = 28
	Message_IBTP_SEND               Message_Type = 29
	Message_IBTP_RECEIPT_SEND       Message_Type = 30
	Message_ROUTER_IBTP_SEND        Message_Type = 31
	Message_ROUTER_IBTP_GET         Message_Type = 32
	Message_ROUTER_IBTP_RECEIPT_GET Message_Type = 33
	Message_ROUTER_INTERCHAIN_GET   Message_Type = 34
	Message_ADDRESS_GET             Message_Type = 35
	Message_ACK                     Message_Type = 36
)

var Message_Type_name = map[int32]string{
	0:  "GET_BLOCK",
	1:  "GET_BLOCK_ACK",
	2:  "CONSENSUS",
	3:  "FETCH_CERT",
	4:  "FETCH_CERT_ACK",
	5:  "FETCH_BLOCK_SIGN",
	6:  "FETCH_BLOCK_SIGN_ACK",
	7:  "FETCH_IBTP_REQUEST_SIGN",
	8:  "FETCH_IBTP_RESPONSE_SIGN",
	9:  "FETCH_IBTP_SIGN_ACK",
	11: "GET_ADDRESS",
	12: "GET_ADDRESS_ACK",
	13: "GET_BLOCK_HEADERS",
	14: "GET_BLOCK_HEADERS_ACK",
	15: "GET_BLOCKS",
	16: "GET_BLOCKS_ACK",
	17: "CHECK_MASTER_PIER",
	18: "CHECK_MASTER_PIER_ACK",
	21: "FETCH_BURN_SIGN",
	22: "FETCH_BURN_SIGN_ACK",
	23: "APPCHAIN_REGISTER",
	24: "APPCHAIN_UPDATE",
	25: "APPCHAIN_GET",
	26: "INTERCHAIN_META_GET",
	27: "RULE_DEPLOY",
	28: "IBTP_GET",
	29: "IBTP_SEND",
	30: "IBTP_RECEIPT_SEND",
	31: "ROUTER_IBTP_SEND",
	32: "ROUTER_IBTP_GET",
	33: "ROUTER_IBTP_RECEIPT_GET",
	34: "ROUTER_INTERCHAIN_GET",
	35: "ADDRESS_GET",
	36: "ACK",
}

var Message_Type_value = map[string]int32{
	"GET_BLOCK":                0,
	"GET_BLOCK_ACK":            1,
	"CONSENSUS":                2,
	"FETCH_CERT":               3,
	"FETCH_CERT_ACK":           4,
	"FETCH_BLOCK_SIGN":         5,
	"FETCH_BLOCK_SIGN_ACK":     6,
	"FETCH_IBTP_REQUEST_SIGN":  7,
	"FETCH_IBTP_RESPONSE_SIGN": 8,
	"FETCH_IBTP_SIGN_ACK":      9,
	"GET_ADDRESS":              11,
	"GET_ADDRESS_ACK":          12,
	"GET_BLOCK_HEADERS":        13,
	"GET_BLOCK_HEADERS_ACK":    14,
	"GET_BLOCKS":               15,
	"GET_BLOCKS_ACK":           16,
	"CHECK_MASTER_PIER":        17,
	"CHECK_MASTER_PIER_ACK":    18,
	"FETCH_BURN_SIGN":          21,
	"FETCH_BURN_SIGN_ACK":      22,
	"APPCHAIN_REGISTER":        23,
	"APPCHAIN_UPDATE":          24,
	"APPCHAIN_GET":             25,
	"INTERCHAIN_META_GET":      26,
	"RULE_DEPLOY":              27,
	"IBTP_GET":                 28,
	"IBTP_SEND":                29,
	"IBTP_RECEIPT_SEND":        30,
	"ROUTER_IBTP_SEND":         31,
	"ROUTER_IBTP_GET":          32,
	"ROUTER_IBTP_RECEIPT_GET":  33,
	"ROUTER_INTERCHAIN_GET":    34,
	"ADDRESS_GET":              35,
	"ACK":                      36,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{0, 0}
}

type Message struct {
	Type    Message_Type `protobuf:"varint,1,opt,name=type,proto3,enum=pb.Message_Type" json:"type,omitempty"`
	Data    []byte       `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	Version []byte       `protobuf:"bytes,3,opt,name=Version,proto3" json:"Version,omitempty"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_8571034d60397816, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Message.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return m.Size()
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() Message_Type {
	if m != nil {
		return m.Type
	}
	return Message_GET_BLOCK
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Message) GetVersion() []byte {
	if m != nil {
		return m.Version
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterType((*Message)(nil), "pb.Message")
}

func init() { proto.RegisterFile("network.proto", fileDescriptor_8571034d60397816) }

var fileDescriptor_8571034d60397816 = []byte{
	// 509 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x93, 0xcf, 0x6e, 0xda, 0x40,
	0x10, 0xc6, 0x31, 0x10, 0x48, 0x26, 0xfc, 0x59, 0x26, 0xa1, 0x38, 0x4d, 0xea, 0x52, 0x9a, 0x43,
	0x4e, 0x1c, 0xda, 0x27, 0x30, 0xf6, 0x16, 0x2c, 0xc0, 0xb8, 0xbb, 0xeb, 0x4a, 0x3d, 0x59, 0x20,
	0x59, 0x55, 0x55, 0x29, 0x58, 0x80, 0x54, 0xe5, 0x2d, 0xfa, 0x30, 0x7d, 0x88, 0x1e, 0x73, 0xe8,
	0xa1, 0xc7, 0x0a, 0x5e, 0xa4, 0x9a, 0x35, 0xd8, 0x34, 0xb9, 0xb1, 0xbf, 0x6f, 0xe6, 0xd3, 0x7c,
	0x33, 0x18, 0xea, 0xf7, 0xf1, 0xe6, 0xfb, 0x72, 0xf5, 0xad, 0x9f, 0xac, 0x96, 0x9b, 0x25, 0x16,
	0x93, 0x45, 0xef, 0x67, 0x05, 0xaa, 0xd3, 0x78, 0xbd, 0x9e, 0x7f, 0x89, 0xf1, 0x16, 0xca, 0x9b,
	0x87, 0x24, 0x36, 0x8d, 0xae, 0x71, 0xd7, 0x78, 0xc7, 0xfa, 0xc9, 0xa2, 0xbf, 0x97, 0xfa, 0xea,
	0x21, 0x89, 0x85, 0x56, 0x11, 0xa1, 0xec, 0xce, 0x37, 0x73, 0xb3, 0xd8, 0x35, 0xee, 0x6a, 0x42,
	0xff, 0x46, 0x13, 0xaa, 0x9f, 0xe2, 0xd5, 0xfa, 0xeb, 0xf2, 0xde, 0x2c, 0x69, 0x7c, 0x78, 0xf6,
	0x7e, 0x9f, 0x40, 0x99, 0x9a, 0xb1, 0x0e, 0x67, 0x43, 0xae, 0xa2, 0xc1, 0x64, 0xe6, 0x8c, 0x59,
	0x01, 0x5b, 0x50, 0xcf, 0x9e, 0x91, 0xed, 0x8c, 0x99, 0x41, 0x15, 0xce, 0xcc, 0x97, 0xdc, 0x97,
	0xa1, 0x64, 0x45, 0x6c, 0x00, 0x7c, 0xe0, 0xca, 0x19, 0x45, 0x0e, 0x17, 0x8a, 0x95, 0x10, 0xa1,
	0x91, 0xbf, 0x75, 0x4b, 0x19, 0x2f, 0x81, 0xa5, 0x2c, 0xf5, 0x91, 0xde, 0xd0, 0x67, 0x27, 0x68,
	0xc2, 0xe5, 0x53, 0xaa, 0xeb, 0x2b, 0x78, 0x0d, 0x9d, 0x54, 0xf1, 0x06, 0x2a, 0x88, 0x04, 0xff,
	0x18, 0x72, 0xa9, 0xd2, 0xb6, 0x2a, 0xde, 0x80, 0xf9, 0x9f, 0x28, 0x03, 0x9a, 0x26, 0x55, 0x4f,
	0xb1, 0x03, 0x17, 0x47, 0x6a, 0xe6, 0x79, 0x86, 0x4d, 0x38, 0xa7, 0x24, 0xb6, 0xeb, 0x0a, 0x2e,
	0x25, 0x3b, 0xc7, 0x0b, 0x68, 0x1e, 0x01, 0x5d, 0x55, 0xc3, 0x36, 0xb4, 0xf2, 0xbc, 0x23, 0x6e,
	0xbb, 0x5c, 0x48, 0x56, 0xc7, 0x2b, 0x68, 0x3f, 0xc3, 0xba, 0xa3, 0x41, 0xf9, 0x33, 0x49, 0xb2,
	0x26, 0xe5, 0xcf, 0xdf, 0xba, 0x86, 0x91, 0xab, 0x33, 0xe2, 0xce, 0x38, 0x9a, 0xda, 0x52, 0x71,
	0x11, 0x05, 0x1e, 0x17, 0xac, 0x45, 0xae, 0xcf, 0xb0, 0xee, 0x40, 0x1a, 0x6e, 0xbf, 0x9b, 0x50,
	0xf8, 0x69, 0xb6, 0x76, 0x9e, 0x2d, 0x83, 0xba, 0xfa, 0x05, 0xf9, 0xdb, 0x41, 0xe0, 0x8c, 0x6c,
	0xcf, 0x8f, 0x04, 0x1f, 0x7a, 0xe4, 0xc6, 0x3a, 0x64, 0x92, 0xe1, 0x30, 0x70, 0x6d, 0xc5, 0x99,
	0x89, 0x0c, 0x6a, 0x19, 0x1c, 0x72, 0xc5, 0xae, 0xc8, 0xd6, 0xf3, 0x15, 0x17, 0x29, 0x9b, 0x72,
	0x65, 0x6b, 0xe1, 0x25, 0xad, 0x4c, 0x84, 0x13, 0x1e, 0xb9, 0x3c, 0x98, 0xcc, 0x3e, 0xb3, 0x6b,
	0xac, 0xc1, 0xa9, 0x5e, 0x2b, 0xc9, 0x37, 0xf4, 0x47, 0x48, 0x97, 0xcc, 0x7d, 0x97, 0xbd, 0xa2,
	0x21, 0xf6, 0x17, 0x71, 0xb8, 0x17, 0xa8, 0x14, 0x5b, 0x74, 0x7b, 0x31, 0x0b, 0x29, 0x5e, 0x5e,
	0xfc, 0x9a, 0x46, 0x3b, 0xa6, 0x64, 0xd8, 0xa5, 0xb3, 0x1f, 0xc3, 0x83, 0x11, 0x89, 0x6f, 0x68,
	0x59, 0x07, 0x31, 0x1f, 0x96, 0xa4, 0x1e, 0xcd, 0x79, 0xb8, 0x22, 0x81, 0xb7, 0x58, 0x85, 0x12,
	0x2d, 0xe6, 0x76, 0x60, 0xfe, 0xda, 0x5a, 0xc6, 0xe3, 0xd6, 0x32, 0xfe, 0x6e, 0x2d, 0xe3, 0xc7,
	0xce, 0x2a, 0x3c, 0xee, 0xac, 0xc2, 0x9f, 0x9d, 0x55, 0x58, 0x54, 0xf4, 0xb7, 0xf5, 0xfe, 0x5f,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x9a, 0xd0, 0xe8, 0xf9, 0x6c, 0x03, 0x00, 0x00,
}

func (m *Message) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Message) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Message) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Version) > 0 {
		i -= len(m.Version)
		copy(dAtA[i:], m.Version)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.Version)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintNetwork(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if m.Type != 0 {
		i = encodeVarintNetwork(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintNetwork(dAtA []byte, offset int, v uint64) int {
	offset -= sovNetwork(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Message) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Type != 0 {
		n += 1 + sovNetwork(uint64(m.Type))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	l = len(m.Version)
	if l > 0 {
		n += 1 + l + sovNetwork(uint64(l))
	}
	return n
}

func sovNetwork(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNetwork(x uint64) (n int) {
	return sovNetwork(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Message) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNetwork
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Message: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Message: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= Message_Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Version", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthNetwork
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthNetwork
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Version = append(m.Version[:0], dAtA[iNdEx:postIndex]...)
			if m.Version == nil {
				m.Version = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNetwork(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNetwork
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNetwork(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNetwork
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNetwork
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNetwork
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNetwork
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNetwork
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNetwork        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNetwork          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNetwork = fmt.Errorf("proto: unexpected end of group")
)
